In [45]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder, MinMaxScaler, StandardScaler
from sklearn.model_selection import train_test_split

In [46]:
data = pd.read_csv(r'C:\Users\srivi\OneDrive\Desktop\flight_price_prediction\flight_price_prediction_dataset\Clean_Dataset.csv')

In [47]:
data.head()

,Unnamed: 0,airline,flight,source_city,departure_time,stops,arrival_time,destination_city,class,duration,days_left,price
0,0,SpiceJet,SG-8709,Delhi,Evening,zero,Night,Mumbai,Economy,2.17,1,5953
1,1,SpiceJet,SG-8157,Delhi,Early_Morning,zero,Morning,Mumbai,Economy,2.33,1,5953
2,2,AirAsia,I5-764,Delhi,Early_Morning,zero,Early_Morning,Mumbai,Economy,2.17,1,5956
3,3,Vistara,UK-995,Delhi,Morning,zero,Afternoon,Mumbai,Economy,2.25,1,5955
4,4,Vistara,UK-963,Delhi,Morning,zero,Morning,Mumbai,Economy,2.33,1,5955

In [48]:
data.stops = pd.factorize(data['stops'])[0]

In [49]:
data

,Unnamed: 0,airline,flight,source_city,departure_time,stops,arrival_time,destination_city,class,duration,days_left,price
0,0,SpiceJet,SG-8709,Delhi,Evening,0,Night,Mumbai,Economy,2.17,1,5953
1,1,SpiceJet,SG-8157,Delhi,Early_Morning,0,Morning,Mumbai,Economy,2.33,1,5953
2,2,AirAsia,I5-764,Delhi,Early_Morning,0,Early_Morning,Mumbai,Economy,2.17,1,5956
3,3,Vistara,UK-995,Delhi,Morning,0,Afternoon,Mumbai,Economy,2.25,1,5955
4,4,Vistara,UK-963,Delhi,Morning,0,Morning,Mumbai,Economy,2.33,1,5955
...,...,...,...,...,...,...,...,...,...,...,...,...
300148,300148,Vistara,UK-822,Chennai,Morning,1,Evening,Hyderabad,Business,10.08,49,69265
300149,300149,Vistara,UK-826,Chennai,Afternoon,1,Night,Hyderabad,Business,10.42,49,77105
300150,300150,Vistara,UK-832,Chennai,Early_Morning,1,Night,Hyderabad,Business,13.83,49,79099
300151,300151,Vistara,UK-828,Chennai,Early_Morning,1,Evening,Hyderabad,Business,10.00,49,81585
300152,300152,Vistara,UK-822,Chennai,Morning,1,Evening,Hyderabad,Business,10.08,49,81585

In [50]:
pd.get_dummies(data['airline'], prefix='airline')

,airline_AirAsia,airline_Air_India,airline_GO_FIRST,airline_Indigo,airline_SpiceJet,airline_Vistara
0,False,False,False,False,True,False
1,False,False,False,False,True,False
2,True,False,False,False,False,False
3,False,False,False,False,False,True
4,False,False,False,False,False,True
...,...,...,...,...,...,...
300148,False,False,False,False,False,True
300149,False,False,False,False,False,True
300150,False,False,False,False,False,True
300151,False,False,False,False,False,True
300152,False,False,False,False,False,True

In [51]:
data = data.join(pd.get_dummies(data['source_city'], prefix='source_city')).drop('source_city', axis=1)
data = data.join(pd.get_dummies(data['destination_city'], prefix='destination_city')).drop('destination_city', axis=1)
data = data.join(pd.get_dummies(data['departure_time'], prefix='departure_time')).drop('departure_time', axis=1)
data = data.join(pd.get_dummies(data['arrival_time'], prefix='arrival_time')).drop('arrival_time', axis=1)

In [52]:
data

,Unnamed: 0,airline,flight,stops,class,duration,days_left,price,source_city_Bangalore,source_city_Chennai,...,departure_time_Evening,departure_time_Late_Night,departure_time_Morning,departure_time_Night,arrival_time_Afternoon,arrival_time_Early_Morning,arrival_time_Evening,arrival_time_Late_Night,arrival_time_Morning,arrival_time_Night
0,0,SpiceJet,SG-8709,0,Economy,2.17,1,5953,False,False,...,True,False,False,False,False,False,False,False,False,True
1,1,SpiceJet,SG-8157,0,Economy,2.33,1,5953,False,False,...,False,False,False,False,False,False,False,False,True,False
2,2,AirAsia,I5-764,0,Economy,2.17,1,5956,False,False,...,False,False,False,False,False,True,False,False,False,False
3,3,Vistara,UK-995,0,Economy,2.25,1,5955,False,False,...,False,False,True,False,True,False,False,False,False,False
4,4,Vistara,UK-963,0,Economy,2.33,1,5955,False,False,...,False,False,True,False,False,False,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
300148,300148,Vistara,UK-822,1,Business,10.08,49,69265,False,True,...,False,False,True,False,False,False,True,False,False,False
300149,300149,Vistara,UK-826,1,Business,10.42,49,77105,False,True,...,False,False,False,False,False,False,False,False,False,True
300150,300150,Vistara,UK-832,1,Business,13.83,49,79099,False,True,...,False,False,False,False,False,False,False,False,False,True
300151,300151,Vistara,UK-828,1,Business,10.00,49,81585,False,True,...,False,False,False,False,False,False,True,False,False,False
300152,300152,Vistara,UK-822,1,Business,10.08,49,81585,False,True,...,False,False,True,False,False,False,True,False,False,False

In [53]:
data['price'].fillna(data['price'].mean())

0          5953
1          5953
2          5956
3          5955
4          5955
          ...
300148    69265
300149    77105
300150    79099
300151    81585
300152    81585
Name: price, Length: 300153, dtype: int64

In [54]:
data['price'].fillna(data['price'].median())

0          5953
1          5953
2          5956
3          5955
4          5955
          ...
300148    69265
300149    77105
300150    79099
300151    81585
300152    81585
Name: price, Length: 300153, dtype: int64

In [55]:
data['price'].fillna(data['price'].mode()[0])

0          5953
1          5953
2          5956
3          5955
4          5955
          ...
300148    69265
300149    77105
300150    79099
300151    81585
300152    81585
Name: price, Length: 300153, dtype: int64

In [56]:
q1=np.quantile(data['price'],0.25) 
q3=np.quantile(data['price'],0.75)

In [57]:
iqr=q3-q1
lower_bound=q1-1.5*iqr
upper_bound=q3+1.5*iqr

In [59]:
data['price']=data[(data['price']<upper_bound)&(data['price']>lower_bound)]['price']

In [62]:
data.head(5)

,Unnamed: 0,airline,flight,stops,class,duration,days_left,price,source_city_Bangalore,source_city_Chennai,...,departure_time_Evening,departure_time_Late_Night,departure_time_Morning,departure_time_Night,arrival_time_Afternoon,arrival_time_Early_Morning,arrival_time_Evening,arrival_time_Late_Night,arrival_time_Morning,arrival_time_Night
0,0,SpiceJet,SG-8709,0,Economy,2.17,1,5953.0,False,False,...,True,False,False,False,False,False,False,False,False,True
1,1,SpiceJet,SG-8157,0,Economy,2.33,1,5953.0,False,False,...,False,False,False,False,False,False,False,False,True,False
2,2,AirAsia,I5-764,0,Economy,2.17,1,5956.0,False,False,...,False,False,False,False,False,True,False,False,False,False
3,3,Vistara,UK-995,0,Economy,2.25,1,5955.0,False,False,...,False,False,True,False,True,False,False,False,False,False
4,4,Vistara,UK-963,0,Economy,2.33,1,5955.0,False,False,...,False,False,True,False,False,False,False,False,True,False

In [ ]:
data.drop(['price',''],axis=1,inplace=True)

In [63]:
data.drop_duplicates(inplace=True) 
data.dropna(inplace=True)

In [64]:
data

,Unnamed: 0,airline,flight,stops,class,duration,days_left,price,source_city_Bangalore,source_city_Chennai,...,departure_time_Evening,departure_time_Late_Night,departure_time_Morning,departure_time_Night,arrival_time_Afternoon,arrival_time_Early_Morning,arrival_time_Evening,arrival_time_Late_Night,arrival_time_Morning,arrival_time_Night
0,0,SpiceJet,SG-8709,0,Economy,2.17,1,5953.0,False,False,...,True,False,False,False,False,False,False,False,False,True
1,1,SpiceJet,SG-8157,0,Economy,2.33,1,5953.0,False,False,...,False,False,False,False,False,False,False,False,True,False
2,2,AirAsia,I5-764,0,Economy,2.17,1,5956.0,False,False,...,False,False,False,False,False,True,False,False,False,False
3,3,Vistara,UK-995,0,Economy,2.25,1,5955.0,False,False,...,False,False,True,False,True,False,False,False,False,False
4,4,Vistara,UK-963,0,Economy,2.33,1,5955.0,False,False,...,False,False,True,False,False,False,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
300148,300148,Vistara,UK-822,1,Business,10.08,49,69265.0,False,True,...,False,False,True,False,False,False,True,False,False,False
300149,300149,Vistara,UK-826,1,Business,10.42,49,77105.0,False,True,...,False,False,False,False,False,False,False,False,False,True
300150,300150,Vistara,UK-832,1,Business,13.83,49,79099.0,False,True,...,False,False,False,False,False,False,False,False,False,True
300151,300151,Vistara,UK-828,1,Business,10.00,49,81585.0,False,True,...,False,False,False,False,False,False,True,False,False,False
300152,300152,Vistara,UK-822,1,Business,10.08,49,81585.0,False,True,...,False,False,True,False,False,False,True,False,False,False

Feature engineering:

In [65]:
data.describe()

,Unnamed: 0,stops,duration,days_left,price
count,300030.000000,300030.000000,300030.000000,300030.000000,300030.000000
mean,150034.147885,0.924188,12.220126,26.012009,20855.326674
std,86638.319536,0.398049,7.192515,13.557878,22638.775853
min,0.000000,0.000000,0.830000,1.000000,1105.000000
25%,75007.250000,1.000000,6.830000,15.000000,4783.000000
50%,150014.500000,1.000000,11.250000,26.000000,7425.000000
75%,225048.750000,1.000000,16.170000,38.000000,42521.000000
max,300152.000000,2.000000,49.830000,49.000000,98972.000000

In [66]:
from sklearn.preprocessing import LabelEncoder 
le=LabelEncoder() 
data['price']=le.fit_transform(data['price'])

In [70]:
from sklearn.preprocessing import MinMaxScaler ,StandardScaler
scaler=StandardScaler() 
data['days_left']=scaler.fit_transform(data['days_left'].values.reshape(-1,1))

In [73]:
X=data.drop(['duration'],axis=1) 
y=data['duration']

In [75]:
X, y = data.drop('duration', axis=1), data['duration']

In [93]:
from sklearn.preprocessing import LabelEncoder 
le=LabelEncoder() 
data['price']=le.fit_transform(data['price'])

In [92]:
from sklearn.metrics import r2_score, mean_squared_error, mean_absolute_error

reg = RandomForestRegressor(n_jobs=-1, random_state=42)
reg.fit(X_train, y_train)

# Evaluate on the test set
y_pred = reg.predict(X_test)
print("R2 score:", r2_score(y_test, y_pred))            
print("MAE:", mean_absolute_error(y_test, y_pred))
print("RMSE:", np.sqrt(mean_squared_error(y_test, y_pred)))

ValueError: could not convert string to float: 'Air_India'

In [ ]:
import warnings
warnings.filterwarnings('ignore')

NotFittedError: This RandomForestRegressor instance is not fitted yet. Call 'fit' with appropriate arguments before using this estimator.